/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

group = "io.scriptor"
version = "1.0.0"
description = "eswin"

java.toolchain.languageVersion.set(JavaLanguageVersion.of(24))

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.jetbrains:annotations:24.0.0")
    implementation("com.formdev:flatlaf:3.6")
}

javafx {
    version = "24.0.2"
    modules = listOf("javafx.controls", "javafx.swing", "javafx.web")
}

application {
    mainClass.set("io.scriptor.eswin.Main")
}
