[libraries]
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "24.0.0" }
formdev-flatlaf = { group = "com.formdev", name = "flatlaf", version = "3.6" }
postgresql-postgresql = { group = "org.postgresql", name = "postgresql", version = "42.7.7" }