[libraries]
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "26.0.0" }
flatlaf = { group = "com.formdev", name = "flatlaf", version = "3.6" }
postgresql = { group = "org.postgresql", name = "postgresql", version = "42.7.7" }